# -*- coding: utf-8 -*-

# Form30 implementation generated from reading ui file 'Ghatna_Form30.ui'
#
# Created: Mon Oct 30 22:26:38 2017
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
import csv
import sqlite3
#from ghatana_csv import create_csv

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form30(object):
    def create_csv(self):
	#with open('ghatana.csv','a') as fp:	
	#	a = csv.writer(fp)
		#flist =[['crime_type','date']]
		
	flist =[] 
	
	c_type =str(self.crime_type.text())
	c_date =str(self.crime_date.text())
	time = str(self.time.text())
	officer = str(self.officer.currentText())
	report_officer = str(self.report_officer.text())	
	info = str(self.info.text())
	direction = str(self.direction.currentText())	
	distance = str(self.distance.text())
	blk_no = str(self.blk_no.text())
	rd_name = str(self.rd_name.text())
	colony = str(self.colony.text())
	city = str(self.city.text())
	tahashil = str(self.tahashil.text())
    	'''if ctimey.isChecked() == true:
		ctimey = str(self.ctimey.text())
		print yes
    	else:
		ctimen = str(self.ctimen.text())	
		print''' 
	'''country = str(self.country.currentText())
	state = str(self.state.currentText())
	jilha = str(self.jilha.text())
	police_station = str(self.police_station.text())
	pincode = str(self.pincode.text())'''
	list1 = [c_type,c_date,time,officer,report_officer,info,direction,distance,blk_no,rd_name,colony,city,tahashil]#,country,state,jilha,police_station,pincode]
	flist.append(list1)
	#a.writerows(flist)
	#print flist
	rows = [c_type, c_date, time, officer, report_officer, info, direction, distance, blk_no, rd_name, colony, city, tahashil]#, country, state, jilha, police_station, pincode]
	con = sqlite3.connect("Analysis.db")
	c = con.cursor()
	#c.execute("create table ghatna(crime_type varchar(40),crime_date DATE,time TIME,officer varchar(25),ctime varchar(10),report_officer varchra(25),info varchar(100),direction varchar(25),distance varchar(25),blk_no int,road_name varchar(25),colony varchar(25),city varchar(25),tahashil varchar(25),perm_add varchar(10),country varchar(25),state varchar(20),jilha varchar(20),police_station varchar(50),pincode int)")			
	sql = "insert into ghatna(crime_type,crime_date,time,officer,report_officer,info,direction,distance,blk_no,road_name,colony,city,tahashil) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"
	print rows
	c.execute(sql, rows)
	c.execute("select * from ghatna")
	x = c.fetchall()
	print x
	con.commit()
	con.close()
	
    def setupUi(self, Form30):
        Form30.setObjectName(_fromUtf8("Form30"))
        Form30.resize(817, 1485)
        self.listView = QtGui.QListView(Form30)
        self.listView.setGeometry(QtCore.QRect(80, 80, 701, 1381))
        self.listView.setObjectName(_fromUtf8("listView"))
        self.pushButton_3 = QtGui.QPushButton(Form30)
        self.pushButton_3.setGeometry(QtCore.QRect(200, 30, 181, 41))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.label_2 = QtGui.QLabel(Form30)
        self.label_2.setGeometry(QtCore.QRect(100, 110, 61, 31))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(Form30)
        self.label_3.setGeometry(QtCore.QRect(100, 150, 51, 31))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(Form30)
        self.label_4.setGeometry(QtCore.QRect(90, 200, 161, 31))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(Form30)
        self.label_5.setGeometry(QtCore.QRect(220, 250, 721, 31))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_8 = QtGui.QLabel(Form30)
        self.label_8.setGeometry(QtCore.QRect(90, 280, 161, 31))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.ctimey = QtGui.QRadioButton(Form30)
        self.ctimey.setGeometry(QtCore.QRect(280, 290, 117, 22))
        self.ctimey.setObjectName(_fromUtf8("radioButton"))
        self.ctimen = QtGui.QRadioButton(Form30)
        self.ctimen.setGeometry(QtCore.QRect(280, 320, 117, 22))
        self.ctimen.setObjectName(_fromUtf8("radioButton_2"))
        self.crime_date = QtGui.QLineEdit(Form30)
        self.crime_date.setGeometry(QtCore.QRect(220, 100, 371, 41))
        self.crime_date.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.crime_date.setInputMask(_fromUtf8("9999"))
        self.crime_date.setMaxLength(10)
        self.crime_date.setObjectName(_fromUtf8("crime_date"))
        self.officer = QtGui.QComboBox(Form30)
        self.officer.setGeometry(QtCore.QRect(220, 200, 371, 41))
        self.officer.setObjectName(_fromUtf8("officer"))
        self.officer.addItem(_fromUtf8("निवडा "))
        self.officer.addItem(_fromUtf8("S.S .Deshpande"))
        self.officer.addItem(_fromUtf8("S.P Jadhav"))
        self.officer.addItem(_fromUtf8("R.M Patil"))
        self.time = QtGui.QLineEdit(Form30)
        self.time.setGeometry(QtCore.QRect(220, 150, 371, 41))
        self.time.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.time.setInputMask(_fromUtf8("99:99:99"))
        self.time.setMaxLength(10)
        self.time.setObjectName(_fromUtf8("time"))
        self.label_6 = QtGui.QLabel(Form30)
        self.label_6.setGeometry(QtCore.QRect(90, 360, 91, 31))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(Form30)
        self.label_7.setGeometry(QtCore.QRect(90, 440, 181, 31))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_9 = QtGui.QLabel(Form30)
        self.label_9.setGeometry(QtCore.QRect(90, 400, 91, 31))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(Form30)
        self.label_10.setGeometry(QtCore.QRect(60, 480, 611, 21))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(Form30)
        self.label_11.setGeometry(QtCore.QRect(90, 520, 121, 31))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(Form30)
        self.label_12.setGeometry(QtCore.QRect(90, 560, 121, 31))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.lineEdit_3 = QtGui.QLineEdit(Form30)
        self.lineEdit_3.setGeometry(QtCore.QRect(260, 340, 371, 41))
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.lineEdit_4 = QtGui.QLineEdit(Form30)
        self.lineEdit_4.setGeometry(QtCore.QRect(260, 390, 371, 41))
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.crime_type = QtGui.QLineEdit(Form30)
        self.crime_type.setGeometry(QtCore.QRect(260, 440, 371, 41))
        self.crime_type.setObjectName(_fromUtf8("crime_type"))
        self.report_officer = QtGui.QLineEdit(Form30)
        self.report_officer.setGeometry(QtCore.QRect(260, 510, 371, 41))
        self.report_officer.setObjectName(_fromUtf8("report_officer"))
        self.info = QtGui.QLineEdit(Form30)
        self.info.setGeometry(QtCore.QRect(260, 560, 371, 41))
        self.info.setObjectName(_fromUtf8("info"))
        self.label_13 = QtGui.QLabel(Form30)
        self.label_13.setGeometry(QtCore.QRect(90, 610, 611, 21))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(Form30)
        self.label_14.setGeometry(QtCore.QRect(110, 680, 151, 21))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(Form30)
        self.label_15.setGeometry(QtCore.QRect(110, 640, 141, 21))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.direction = QtGui.QComboBox(Form30)
        self.direction.setGeometry(QtCore.QRect(270, 630, 371, 41))
        self.direction.setObjectName(_fromUtf8("direction"))	
        self.direction.addItem(_fromUtf8("निवडा "))
        self.direction.addItem(_fromUtf8("East"))
        self.direction.addItem(_fromUtf8("West"))
        self.direction.addItem(_fromUtf8("North"))
        self.direction.addItem(_fromUtf8("South"))
        self.distance = QtGui.QLineEdit(Form30)
        self.distance.setGeometry(QtCore.QRect(270, 680, 371, 41))
        self.distance.setObjectName(_fromUtf8("distance"))
        self.label_16 = QtGui.QLabel(Form30)
        self.label_16.setGeometry(QtCore.QRect(80, 740, 611, 21))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_32 = QtGui.QLabel(Form30)
        self.label_32.setGeometry(QtCore.QRect(100, 1050, 211, 31))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.label_21 = QtGui.QLabel(Form30)
        self.label_21.setGeometry(QtCore.QRect(100, 780, 111, 21))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.label_22 = QtGui.QLabel(Form30)
        self.label_22.setGeometry(QtCore.QRect(100, 830, 111, 21))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.label_24 = QtGui.QLabel(Form30)
        self.label_24.setGeometry(QtCore.QRect(100, 940, 111, 21))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.label_23 = QtGui.QLabel(Form30)
        self.label_23.setGeometry(QtCore.QRect(100, 990, 111, 21))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.label_25 = QtGui.QLabel(Form30)
        self.label_25.setGeometry(QtCore.QRect(100, 890, 131, 21))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.blk_no = QtGui.QLineEdit(Form30)
        self.blk_no.setGeometry(QtCore.QRect(310, 770, 371, 41))
        self.blk_no.setObjectName(_fromUtf8("blk_no"))
        self.rd_name = QtGui.QLineEdit(Form30)
        self.rd_name.setGeometry(QtCore.QRect(310, 820, 371, 41))
        self.rd_name.setObjectName(_fromUtf8("rd_name"))
        self.colony = QtGui.QLineEdit(Form30)
        self.colony.setGeometry(QtCore.QRect(310, 870, 371, 41))
        self.colony.setObjectName(_fromUtf8("colony"))
        self.tahashil = QtGui.QLineEdit(Form30)
        self.tahashil.setGeometry(QtCore.QRect(310, 990, 371, 41))
        self.tahashil.setObjectName(_fromUtf8("tahashil"))
        self.city = QtGui.QLineEdit(Form30)
        self.city.setGeometry(QtCore.QRect(310, 930, 371, 41))
        self.city.setObjectName(_fromUtf8("city"))
        self.perm_addy = QtGui.QRadioButton(Form30)
        self.perm_addy.setGeometry(QtCore.QRect(330, 1060, 117, 22))
        self.perm_addy.setObjectName(_fromUtf8("perm_addy"))
        self.perm_addn = QtGui.QRadioButton(Form30)
        self.perm_addn.setGeometry(QtCore.QRect(330, 1100, 117, 22))
        self.perm_addn.setObjectName(_fromUtf8("perm_addn"))
        self.label_27 = QtGui.QLabel(Form30)
        self.label_27.setGeometry(QtCore.QRect(110, 1210, 111, 21))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.label_28 = QtGui.QLabel(Form30)
        self.label_28.setGeometry(QtCore.QRect(110, 1290, 71, 31))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.label_29 = QtGui.QLabel(Form30)
        self.label_29.setGeometry(QtCore.QRect(110, 1250, 111, 21))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.label_26 = QtGui.QLabel(Form30)
        self.label_26.setGeometry(QtCore.QRect(110, 1170, 111, 21))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.label_30 = QtGui.QLabel(Form30)
        self.label_30.setGeometry(QtCore.QRect(110, 1350, 111, 21))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.pushButton_4 = QtGui.QPushButton(Form30)
        self.pushButton_4.setGeometry(QtCore.QRect(430, 1410, 99, 27))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.country = QtGui.QComboBox(Form30)
        self.country.setGeometry(QtCore.QRect(270, 1160, 371, 41))
        self.country.setObjectName(_fromUtf8("country"))
        self.country.addItem(_fromUtf8(""))
        self.country.addItem(_fromUtf8("India"))
               
        self.state = QtGui.QComboBox(Form30)
        self.state.setGeometry(QtCore.QRect(270, 1200, 371, 41))
        self.state.setObjectName(_fromUtf8("state"))
        self.state.addItem(_fromUtf8("Andhra Pradesh "))
        self.state.addItem(_fromUtf8("Arunachal Pradesh"))
        self.state.addItem(_fromUtf8("Assam"))
        self.state.addItem(_fromUtf8("Bihar"))
        self.state.addItem(_fromUtf8("Goa"))
        self.state.addItem(_fromUtf8("Gujarat"))
        self.state.addItem(_fromUtf8("Haryana"))
        self.state.addItem(_fromUtf8("Himachal Pradesh"))
        self.state.addItem(_fromUtf8("Jammu & Kashmir"))
        self.state.addItem(_fromUtf8("Karnataka"))
        self.state.addItem(_fromUtf8("Kerala"))
        self.state.addItem(_fromUtf8("Madhya Pradesh"))
        self.state.addItem(_fromUtf8("Maharashtra"))
        self.state.addItem(_fromUtf8("Manipur"))
        self.state.addItem(_fromUtf8("Meghalaya"))
        self.state.addItem(_fromUtf8("Mizoram"))
        self.state.addItem(_fromUtf8("Nagaland"))
        self.state.addItem(_fromUtf8("Orissa"))
        self.state.addItem(_fromUtf8("Punjab"))
        self.state.addItem(_fromUtf8("Rajasthan"))
        self.state.addItem(_fromUtf8("Sikkim"))
        self.state.addItem(_fromUtf8("Tamil Nadu"))
        self.state.addItem(_fromUtf8("Tripura"))
        self.state.addItem(_fromUtf8("Uttar Pradesh"))
        self.state.addItem(_fromUtf8("West Bengal"))
        self.state.addItem(_fromUtf8("Chhattisgarh"))
        self.state.addItem(_fromUtf8("Uttarakhand"))
        self.state.addItem(_fromUtf8("Jharkhand"))
        self.state.addItem(_fromUtf8("Telangana"))
        self.pincode = QtGui.QLineEdit(Form30)
        self.pincode.setGeometry(QtCore.QRect(270, 1350, 371, 41))
        self.pincode.setObjectName(_fromUtf8("pincode"))
        self.btn_csv_create = QtGui.QPushButton(Form30)
        self.btn_csv_create.setGeometry(QtCore.QRect(660, 560, 99, 27))
        self.btn_csv_create.setObjectName(_fromUtf8("btn_csv_create"))
        #####################################################################

        self.btn_csv_create.clicked.connect(self.create_csv)

	####################################################################
        self.jilha = QtGui.QLineEdit(Form30)
        self.jilha.setGeometry(QtCore.QRect(270, 1250, 371, 41))
        self.jilha.setObjectName(_fromUtf8("jilha"))
        self.police_station = QtGui.QLineEdit(Form30)
        self.police_station.setGeometry(QtCore.QRect(270, 1300, 371, 41))
        self.police_station.setObjectName(_fromUtf8("police_station"))

        self.retranslateUi(Form30)
        QtCore.QMetaObject.connectSlotsByName(Form30)

    def retranslateUi(self, Form30):
        Form30.setWindowTitle(_translate("Form30", "घटना", None))
        self.pushButton_3.setText(_translate("Form30", "घटना ", None))
        self.label_2.setText(_translate("Form30", "वर्ष", None))
        self.label_3.setText(_translate("Form30", "वेळ*", None))
        self.label_4.setText(_translate("Form30", "या अधिकाऱ्यासाठी नोंद ", None))
        self.label_5.setText(_translate("Form30", "         पोलिस ठाण्यात मिळालेली माहिती", None))
        self.label_8.setText(_translate("Form30", "घटना घडल्याची वेळ आहे", None))
        self.ctimey.setText(_translate("Form30", "     ज्ञात ", None))
        self.ctimen.setText(_translate("Form30", "अज्ञात", None))
        self.officer.setItemText(0, _translate("Form30", "निवडा ", None))
        self.officer.setItemText(1, _translate("Form30", "S.S .Deshpande", None))
        self.officer.setItemText(2, _translate("Form30", "S.P Jadhav", None))
        self.officer.setItemText(3, _translate("Form30", "R.M Patil", None))
        self.direction.setItemText(0, _translate("Form30", "निवडा ", None))
        self.direction.setItemText(1, _translate("Form30", "EAST ", None))
        self.direction.setItemText(2, _translate("Form30", "WEST ", None))
        self.direction.setItemText(3, _translate("Form30", "NORTH ", None))
        self.direction.setItemText(4, _translate("Form30", "SOUTH", None))
        self.label_6.setText(_translate("Form30", "पासून(तारीख)*", None))
        self.label_7.setText(_translate("Form30", "गुन्हा चा प्रकार ", None))
        self.label_9.setText(_translate("Form30", "पर्यंत (तारीख)", None))
        self.label_10.setText(_translate("Form30", "                                                                        विलंबाचे कारण ", None))
        self.label_11.setText(_translate("Form30", "पोलिसांनी नोंद केलेली", None))
        self.label_12.setText(_translate("Form30", "तक्रारदाराने माहिती देणे", None))
        self.label_13.setText(_translate("Form30", "                                                           पोलिस ठाण्यापासून दिशा व अंतर ", None))
        self.label_14.setText(_translate("Form30", "पोलिस ठाण्यापासूनचे अंतर ", None))
        self.label_15.setText(_translate("Form30", "पोलिस ठाण्यापासून दिशा ", None))
        self.direction.setItemText(0, _translate("Form30", "निवडा ", None))
        self.direction.setItemText(1, _translate("Form30", "East", None))
        self.direction.setItemText(2, _translate("Form30", "West", None))
        self.direction.setItemText(3, _translate("Form30", "North", None))
        self.direction.setItemText(4, _translate("Form30", "South", None))
        self.label_16.setText(_translate("Form30", "                                                                                   घटनास्थळ ", None))
        self.label_32.setText(_translate("Form30", "सध्याचा पत्ता कायमच्या पत्याप्रमाणे आहे *", None))
        self.label_21.setText(_translate("Form30", "घर नं ", None))
        self.label_22.setText(_translate("Form30", "रस्त्याचे नाव", None))
        self.label_24.setText(_translate("Form30", "गाव/शहर ", None))
        self.label_23.setText(_translate("Form30", "तहसिल/गट/मंडळ ", None))
        self.label_25.setText(_translate("Form30", "वसाहत/परिसर/ क्षेत्र", None))
        self.perm_addy.setText(_translate("Form30", "होय ", None))
        self.perm_addn.setText(_translate("Form30", "नाही ", None))
        self.label_27.setText(_translate("Form30", "राज्य *", None))
        self.label_28.setText(_translate("Form30", "      \n"
"पोलीस ठाणे    ", None))
        self.label_29.setText(_translate("Form30", "जिल्हा *", None))
        self.label_26.setText(_translate("Form30", "देश *", None))
        self.label_30.setText(_translate("Form30", "पिन कोड", None))
        self.pushButton_4.setText(_translate("Form30", "रिक्त करा ", None))
        self.country.setItemText(0, _translate("Form30", "निवडा", None))
        self.country.setItemText(1, _translate("Form30", "India", None))
        self.state.setItemText(0, _translate("Form30", "निवडा ", None))
        self.state.setItemText(1, _translate("Form30", "आंध्र प्रदेश ", None))
        self.state.setItemText(2, _translate("Form30", "अरुणाचल प्रदेश ", None))
        self.state.setItemText(3, _translate("Form30", "बिहार ", None))
        self.state.setItemText(4, _translate("Form30", "छत्तीसगड ", None))
        self.state.setItemText(5, _translate("Form30", "गोआ ", None))
        self.state.setItemText(6, _translate("Form30", "गुजरात ", None))
        self.state.setItemText(7, _translate("Form30", "हरियाणा ", None))
        self.state.setItemText(8, _translate("Form30", "हिमाचल प्रदेश ", None))
        self.state.setItemText(9, _translate("Form30", "जम्मू काश्मीर ", None))
        self.state.setItemText(10, _translate("Form30", "झारखंड ", None))
        self.state.setItemText(11, _translate("Form30", "कर्नाटक ", None))
        self.state.setItemText(12, _translate("Form30", "केरळ ", None))
        self.state.setItemText(13, _translate("Form30", "मध्यप्रदेश ", None))
        self.state.setItemText(14, _translate("Form30", "महाराष्ट्र ", None))
        self.state.setItemText(15, _translate("Form30", "मणिपूर ", None))
        self.state.setItemText(16, _translate("Form30", "मेघालय ", None))
        self.state.setItemText(17, _translate("Form30", "मेघालय ", None))
        self.state.setItemText(18, _translate("Form30", "नागालँड ", None))
        self.state.setItemText(19, _translate("Form30", "उडीसा ", None))
        self.state.setItemText(20, _translate("Form30", "पंजाब ", None))
        self.state.setItemText(21, _translate("Form30", "राजस्थान", None))
        self.state.setItemText(22, _translate("Form30", "सिक्कम ", None))
        self.state.setItemText(23, _translate("Form30", "तामिळनाडू ", None))
        self.state.setItemText(24, _translate("Form30", "तेलंगणा ", None))
        self.state.setItemText(25, _translate("Form30", "तिरपुरा ", None))
        self.state.setItemText(26, _translate("Form30", "उत्तर प्रदेश ", None))
        self.state.setItemText(27, _translate("Form30", "उत्तरांचल ", None))
        self.state.setItemText(28, _translate("Form30", "पश्चिम बंगाल ", None))
        
        self.btn_csv_create.setText(_translate("Form30", "जतन करा ", None))
        

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Form30 = QtGui.QWidget()
    ui = Ui_Form30()
    ui.setupUi(Form30)
    Form30.show()
    sys.exit(app.exec_())

